#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

path_to_file=$1
ip=$2
username=$3
pathto_ssh_key=$4

scp -o "StrictHostKeyChecking=no" -i "$pathto_ssh_key" "$path_to_file" "$username@$ip:~/"
