#!/usr/bin/env bash

# command to install nginx

sudo apt-get update

sudo apt-get install -y nginx

sudo 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload
