#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_redirection="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Juweria86 permanent;"

sudo sed -i "s/server_name -;/$string_redirection/" /etc/nginx/sites-enabled/default

sudo service nginx restart
